# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 83883690+HashMapsData2Value@users.noreply.github.com
author_name: HashMapsData2Value
cloud_provider: none
preset_name: production
project_name: auditor-frontend

