# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 83883690+HashMapsData2Value@users.noreply.github.com
author_name: HashMapsData2Value
contract_name: auditor
deployment_language: python
preset_name: production
project_name: auditor-contracts

